kind: Secret
apiVersion: v1
metadata:
  name: github-oauth-config
  namespace: devspaces 
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: oauth-scm-configuration
  annotations:
    che.eclipse.org/oauth-scm-server: github
    che.eclipse.org/scm-server-endpoint: github.com
    che.eclipse.org/scm-github-disable-subdomain-isolation: "true" 
type: Opaque
data:
  id: T3YyM2xpcWJYaTlwMWxVWWtBb1UK
  secret: ZjJhMzU5OTY0ZjIwY2Y3ZTFhMzFiMWQwNDA0YWU3NGE5ZTU3NDNiYwo=
